/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FabricRouteRouteImport } from './routes/fabric/route'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as FabricIndexRouteImport } from './routes/fabric/index'
import { Route as FabricExploreRouteImport } from './routes/fabric/explore'
import { Route as FabricIntegrationsRouteImport } from './routes/fabric/integrations'
import { Route as ModelModelIdRouteImport } from './routes/model.$modelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricRouteRoute = FabricRouteRouteImport.update({
  id: '/fabric',
  path: '/fabric',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricIndexRoute = FabricIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FabricRouteRoute,
} as any)
const FabricExploreRoute = FabricExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => FabricRouteRoute,
} as any)
const FabricIntegrationsRoute = FabricIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => FabricRouteRoute,
} as any)
const ModelModelIdRoute = ModelModelIdRouteImport.update({
  id: '/model/$modelId',
  path: '/model/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fabric': typeof FabricRouteRouteWithChildren
  '/models': typeof ModelsRoute
  '/fabric/explore': typeof FabricExploreRoute
  '/fabric/integrations': typeof FabricIntegrationsRoute
  '/model/$modelId': typeof ModelModelIdRoute
  '/fabric/': typeof FabricIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/models': typeof ModelsRoute
  '/fabric/explore': typeof FabricExploreRoute
  '/fabric/integrations': typeof FabricIntegrationsRoute
  '/model/$modelId': typeof ModelModelIdRoute
  '/fabric': typeof FabricIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fabric': typeof FabricRouteRouteWithChildren
  '/models': typeof ModelsRoute
  '/fabric/explore': typeof FabricExploreRoute
  '/fabric/integrations': typeof FabricIntegrationsRoute
  '/model/$modelId': typeof ModelModelIdRoute
  '/fabric/': typeof FabricIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fabric'
    | '/models'
    | '/fabric/explore'
    | '/fabric/integrations'
    | '/model/$modelId'
    | '/fabric/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/models'
    | '/fabric/explore'
    | '/fabric/integrations'
    | '/model/$modelId'
    | '/fabric'
  id:
    | '__root__'
    | '/'
    | '/fabric'
    | '/models'
    | '/fabric/explore'
    | '/fabric/integrations'
    | '/model/$modelId'
    | '/fabric/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FabricRouteRoute: typeof FabricRouteRouteWithChildren
  ModelsRoute: typeof ModelsRoute
  ModelModelIdRoute: typeof ModelModelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabric': {
      id: '/fabric'
      path: '/fabric'
      fullPath: '/fabric'
      preLoaderRoute: typeof FabricRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabric/': {
      id: '/fabric/'
      path: '/'
      fullPath: '/fabric/'
      preLoaderRoute: typeof FabricIndexRouteImport
      parentRoute: typeof FabricRouteRoute
    }
    '/fabric/explore': {
      id: '/fabric/explore'
      path: '/explore'
      fullPath: '/fabric/explore'
      preLoaderRoute: typeof FabricExploreRouteImport
      parentRoute: typeof FabricRouteRoute
    }
    '/fabric/integrations': {
      id: '/fabric/integrations'
      path: '/integrations'
      fullPath: '/fabric/integrations'
      preLoaderRoute: typeof FabricIntegrationsRouteImport
      parentRoute: typeof FabricRouteRoute
    }
    '/model/$modelId': {
      id: '/model/$modelId'
      path: '/model/$modelId'
      fullPath: '/model/$modelId'
      preLoaderRoute: typeof ModelModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FabricRouteRouteChildren {
  FabricExploreRoute: typeof FabricExploreRoute
  FabricIntegrationsRoute: typeof FabricIntegrationsRoute
  FabricIndexRoute: typeof FabricIndexRoute
}

const FabricRouteRouteChildren: FabricRouteRouteChildren = {
  FabricExploreRoute: FabricExploreRoute,
  FabricIntegrationsRoute: FabricIntegrationsRoute,
  FabricIndexRoute: FabricIndexRoute,
}

const FabricRouteRouteWithChildren = FabricRouteRoute._addFileChildren(
  FabricRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FabricRouteRoute: FabricRouteRouteWithChildren,
  ModelsRoute: ModelsRoute,
  ModelModelIdRoute: ModelModelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
